### ISSUE TITLE
关于groupsoftmax调用的问题

### ISSUE THREAD

**Issue by Yanda95** [chengzhengxin/groupsoftmax-simpledet#2]
您好，我看您这边code在调用的时候直接调用mx.sys.contrib.GroupSoftmaxOutput即可，但是我没有找到对应的python文件，只有cu、cc以及cpp，请问一下这个编译后生成文件的位置在哪里？
还有，就是对应cu文件里这个groupsoftmaxgrad的函数应该是反传？那么forward的部分在哪里？

**Comment by chengzhengxin** [comment]
Mxnet框架在写好对应的cpp和cu之后，是不需要单独写python接口的，只要register了这个operator，python就能够调用了。

**Comment by ylc2580** [comment]
你好，请问你那边能按照作者的过程训练起来groupsoftmax这个吗？
